version: "3.7"
services:
  lido-depositor-bot:
    image: lidofinance/depositor-bot
    build: .
    container_name: lido-depositor-bot
    restart: unless-stopped
    ports:
      - 127.0.0.1:9000:9000
    environment:
      - NETWORK=${NETWORK}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - KAFKA_BROKER_ADDRESS_1=${KAFKA_BROKER_ADDRESS_1}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    command: src/depositor.py

  lido-pause-bot:
    image: lidofinance/depositor-bot
    build: .
    container_name: lido-pause-bot
    restart: unless-stopped
    ports:
      - 127.0.0.1:9001:9000
    environment:
      - NETWORK=${NETWORK}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - KAFKA_BROKER_ADDRESS_1=${KAFKA_BROKER_ADDRESS_1}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    command: src/pauser.py
