[tool.poetry]
name = "depositor-bot"
version = "4.1.0"
description = "Bot that collects council signatures, checks blockchain state and signatures and do deposits. Also pause bot send pause tx if there is security warning."
authors = ["Raman <raman.s@lido.fi>"]
license = "MIT License"
readme = "README.md"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "1.23.3"
prometheus-client = "0.14.1"
web3-multi-provider = "^0.6.0"
schema = "^0.7.5"
web3 = "^5.30.0"
flashbots = "^1.0.2"
websocket-client = "^1.4.1"
confluent-kafka = "^2.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"

[tool.pytest.ini_options]
pythonpath = [
  "src",
  "tests",
]
