name: Tests and checks

on: 
  push:

jobs:
  tests:
    name: App tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | python - && echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        env:
          POETRY_VERSION: 1.4.2

      - name: Install dependencies
        run: |
          poetry install

      - name: Unit Tests with pytest
        run: |
          poetry run pytest tests -m unit

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - run: npm install --save-dev hardhat

      - name: Run hardhat
        run: |
          npx hardhat node --fork ${{ secrets.WEB3_RPC_ENDPOINT }} &

      - name: Integration Tests with pytest
        run: |
          poetry run pytest tests -m integration
        env:
          WEB3_RPC_ENDPOINTS: http://127.0.0.1:8545
          DEPOSIT_CONTRACT: "0xff50ed3d0ec03aC01D4C79aAd74928BFF48a7b2b"
          LIDO_LOCATOR: "0x1eDf09b5023DC86737b59dE68a8130De878984f5"

  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
    permissions:
      security-events: write
      contents: read

  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master

  actions:
    uses: lidofinance/linters/.github/workflows/actions.yml@master
